---
- name: Run Script to Install and configure Jenkins
  hosts: jenkins
  become: true

  tasks:
    - name: Copy script
      copy:
        src: ../scripts/jenkins.sh
        dest: /jenkins.sh
        mode: '0755'
    
    - name: Running remote Script
      script:
        executable: /bin/bash
        script: /jenkins.sh