---
- name: Update
  hosts: jenkins
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: dist

  - name: Clean up apt cache
    apt:
      autoclean: yes

  - name: Install Ansible
    apt:
      name: ansible
      state: present